---
title: "Untitled"
format: html
editor: source
---

```{r setup}
library(tidyverse)
library(taylor)
library(GGally)
library(cowplot)
library(ggbeeswarm)
theme_set(theme_minimal( base_size = 20)    ) 
preset <-  theme(panel.background = element_rect("white"))
  
  #fill, colour, size,linetype, color))
```



## Collinearity

```{r}
#| warning: false
#| message: false
taylor_album_songs |> 
  select(album_name, where(is.numeric), -key, -instrumentalness) |> 
  select(-mode, -track_number, -time_signature) |> 
  select(1:9) |> 
GGally::ggpairs(aes(fill = album_name)) +
  scale_fill_albums()
```

```{r}
taylor::album_palettes
```

## Album length by time{.backdrop2}

```{r}
taylor_album_songs |> 
  group_by(album_name, album_release) |> 
  summarize(n_songs = n()) |> 
  relocate(n_songs) |> 
  ggplot() +
  aes(x = album_release, y = n_songs) +
  geom_point()

```

## Album length
```{r}
scale_factor <- 12
mus2hms <- function(x){
  format(hms::as_hms(sum(round(duration_ms/1000, 0), na.rm = TRUE)), "%H:%M:%s")
}

taylor_album_songs |>
  mutate(album_year = paste0(album_name, " (", lubridate::year(album_release), ")")) |>
  mutate(
    album_duration = format(hms::as_hms(sum(
      round(duration_ms / 1000, 0), na.rm = TRUE
    )), "%H:%M:%s")
    ,
    .by = album_name
  )|>
  mutate(song_duration = format(hms::as_hms(round(duration_ms / 1000, 0)  )), "%H:%M:%s",
    album_display_length = album_duration) |> 
  arrange(album_release) |> 
  relocate(contains("duration"))-> album_input 

  ggplot(album_input) +
  aes(y = fct_inorder(album_year)) +
  geom_bar(aes(fill = album_name )) +

  geom_text(aes(label = album_duration),
            stat='count',
            color = "white",
            hjust = 1.2) +
  scale_fill_albums() +
#  scale_x_continuous(sec.axis = sec_axis()) +
   geom_jitter(data = album_input,
              aes(x =song_duration),
              alpha = 0.5, color = "pink",
              width = 0.2, height = 0.2, size = 3) +
  theme(legend.position = "none") +
    scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
#    guide_axis(n.dodge=3)) +
  labs(title = "Taylor Swift's albums",
       y = NULL,
       x = NULL)
```